version: "3.7"

services:
  nodered:
    image: nodered/node-red:latest
    ports:
      - "1880:1880"
    volumes:
      - node_red_data:/data
    environment:
      - TZ=Europe/Amsterdam
    networks:
      - node-red-net

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - nodered
    networks:
      - node-red-net

volumes:
  node_red_data:

networks:
  node-red-net:

